name: Deploy Flask App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd ~/flask_app

          echo "Pulling latest code..."
          git pull origin main

          echo "Restarting app..."

          pkill gunicorn || true

          nohup gunicorn app:app --bind 0.0.0.0:5000 &

          echo "Deployment completed"

          EOF